-------------------------------------------------------------------------------
--- TES3MP types
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
--- tes3mp
-------------------------------------------------------------------------------

---@type TES3MP
tes3mp = tes3mp

---@class TES3MP
---@field _MessageBox fun(pid: number, id: number, label: string)
---@field AddActor fun()
---@field AddAlliedPlayerForPlayer fun(pid: number, otherPid: number)
---@field AddBook fun(pid: number, bookId: string)
---@field AddCellToReset fun(cellDescription: string)
---@field AddClientGlobalFloat fun(variableId: number, value: number)
---@field AddClientGlobalInteger fun(variableId: number, variableBroadType: integer, value: integer)
---@field AddContainerItem fun()
---@field AddCooldownSpell fun(pid: number, spellId: string, startDay: integer, startHour: number)
---@field AddDataFileRequirement fun(name: string, checksum: string)
---@field AddDestinationOverride fun(oldCellDescription: string, newCellDesctiption: string)
---@field AddEnforcedCollisionRefId fun(refId: string)
---@field AddFaction fun(pid: number)
---@field AddItemChange fun(pid: number, refId: string, count: number, charge: number, enchantmentCharge: number, soul: string)
---@field AddJournalEntry fun(pid: number, quest: string, index: integer, actorRefId: string)
---@field AddJournalEntryWithTimestamp fun(pid: number, quest: string, index: integer, actorRefId: string, daysPassed: number, month: number, day: number)
---@field AddJournalIndex fun(pid: number, quest: string, index: integer)
---@field AddKill fun(refId: string, number: number)
---@field AddObject fun()
---@field AddPluginHash fun(pluginName: string, hash: string)
---@field AddQuickKey fun(pid: number, slot: number, type: number, itemId: string)
---@field AddRecord fun()
---@field AddRecordBodyPart fun()
---@field AddRecordEffect fun()
---@field AddRecordInventoryItem fun()
---@field AddSpell fun(pid: number, spellId: string)
---@field AddSynchronizedClientGlobalId fun(globalId: string)
---@field AddSynchronizedClientScriptId fun(scriptId: string)
---@field AddTopic fun(pid: number, topicId: string)
---@field BanAddress fun(ipAddress: string)
---@field CleanChat fun()
---@field CleanChatForPid fun(pid: number)
---@field ClearActorList fun()
---@field ClearAlliedPlayersForPlayer fun(pid: number)
---@field ClearAttributeModifier fun(pid: number, attributeId: number)
---@field ClearBookChanges fun(pid: number)
---@field ClearCellsToReset fun()
---@field ClearClientGlobals fun()
---@field ClearCooldownChanges fun(pid: number)
---@field ClearDestinationOverrides fun()
---@field ClearEnforcedCollisionRefIds fun()
---@field ClearFactionChanges fun(pid: number)
---@field ClearGameSettingValues fun(pid: number)
---@field ClearInventoryChanges fun(pid: number)
---@field ClearJournalChanges fun(pid: number)
---@field ClearKillChanges fun()
---@field ClearMapChanges fun()
---@field ClearObjectList fun()
---@field ClearQuickKeyChanges fun(pid: number)
---@field ClearRecords fun()
---@field ClearSkillModifier fun(pid: number, skillId: number)
---@field ClearSpellbookChanges fun(pid: number)
---@field ClearSynchronizedClientGlobalIds fun()
---@field ClearSynchronizedClientScriptIds fun()
---@field ClearTopicChanges fun(pid: number)
---@field ClearVRSettingValues fun(pid: number)
---@field CopyReceivedActorListToStore fun()
---@field CopyReceivedObjectListToStore fun()
---@field CopyReceivedWorldstateToStore fun()
---@field CreateTimer fun(functionName: string, milliseconds: number): number
---@field CreateTimerEx fun(functionName: string, milliseconds: number, argTypes: string, ...): number
---@field CustomMessageBox fun(pid: number, id: number, label: string, buttons: string)
---@field DoesActorHavePlayerKiller fun(index: integer): boolean
---@field DoesActorHavePosition fun(index: integer): boolean
---@field DoesActorHaveStatsDynamic fun(index: integer): boolean
---@field DoesActorSpellsActiveHavePlayerCaster fun(packetIndex: integer, spellIndex: integer): boolean
---@field DoesFileExist fun(filePath: string): boolean
---@field DoesFilePathExist fun(path: string): boolean
---@field DoesObjectHaveContainer fun(index: integer): boolean
---@field DoesObjectHavePlayerActivating fun(index: integer): boolean
---@field DoesObjectHavePlayerHitting fun(packetIndex: integer): boolean
---@field DoesObjectHavePlayerSummoner fun(index: integer): boolean
---@field DoesPlayerHavePlayerKiller fun(pid: number): boolean
---@field DoesSpellsActiveHavePlayerCaster fun(pid: number, changesIndex: integer): boolean
---@field EquipActorItem fun(slot: number, refId: string, count: number, charge: number, enchantmentCharge : number)
---@field EquipItem fun(pid: number, slot: number, refId: string, count: number, charge: number, enchantmentCharge: number)
---@field GenerateRandomString fun(length: number): string
---@field GetActorCell fun(index: integer): string
---@field GetActorDeathState fun(packetIndex: integer): integer
---@field GetActorEquipmentItemCharge fun(index: integer, slot: number): number
---@field GetActorEquipmentItemCount fun(index: integer, slot: number): number
---@field GetActorEquipmentItemEnchantmentCharge fun(index: integer, slot: number): number
---@field GetActorEquipmentItemRefId fun(index: integer, slot: number): string
---@field GetActorFatigueBase fun(index: integer): number
---@field GetActorFatigueCurrent fun(index: integer): number
---@field GetActorFatigueModified fun(index: integer): number
---@field GetActorHealthBase fun(index: integer): number
---@field GetActorHealthCurrent fun(index: integer): number
---@field GetActorHealthModified fun(index: integer): number
---@field GetActorKillerMpNum fun(index: integer): number
---@field GetActorKillerName fun(index: integer): string
---@field GetActorKillerPid fun(index: integer): number
---@field GetActorKillerRefId fun(index: integer): string
---@field GetActorKillerRefNum fun(index: integer): number
---@field GetActorListAction fun(): number
---@field GetActorListSize fun(): number
---@field GetActorMagickaBase fun(index: integer): number
---@field GetActorMagickaCurrent fun(index: integer): number
---@field GetActorMagickaModified fun(index: integer): number
---@field GetActorMpNum fun(index: integer): number
---@field GetActorPosX fun(index: integer): number
---@field GetActorPosY fun(index: integer): number
---@field GetActorPosZ fun(index: integer): number
---@field GetActorRefId fun(index: integer): string
---@field GetActorRefNum fun(index: integer): number
---@field GetActorRotX fun(index: integer): number
---@field GetActorRotY fun(index: integer): number
---@field GetActorRotZ fun(index: integer): number
---@field GetActorSpellsActiveCasterPid fun(packetIndex, spellIndex): integer
---@field GetActorSpellsActiveCasterRefId fun(packetIndex: integer, spellIndex: integer): string
---@field GetActorSpellsActiveCasterRefNum fun(packetIndex: integer, spellIndex: integer): integer
---@field GetActorSpellsActiveChangesAction fun(packetIndex: integer): integer
---@field GetActorSpellsActiveChangesSize fun(packetIndex: integer): integer
---@field GetActorSpellsActiveDisplayName fun(packetIndex: integer, spellIndex: integer): string
---@field GetActorSpellsActiveEffectArg fun(packetIndex: integer, spellIndex: integer, effectIndex: integer): integer
---@field GetActorSpellsActiveEffectCount fun(packetIndex: integer, spellIndex: integer): integer
---@field GetActorSpellsActiveEffectDuration fun(packetIndex: integer, spellIndex: integer, effectIndex: integer): number
---@field GetActorSpellsActiveEffectId fun(packetIndex: integer, spellIndex: integer, effectIndex: integer): integer
---@field GetActorSpellsActiveEffectMagnitude fun(packetIndex: integer, spellIndex: integer, effectIndex: integer): number
---@field GetActorSpellsActiveEffectTimeLeft fun(packetIndex: integer, spellIndex: integer, effectIndex: integer): number
---@field GetActorSpellsActiveId fun(packetIndex: integer, spellIndex: integer): string
---@field GetActorSpellsActiveStackingState fun(packetIndex: integer, spellIndex: integer): boolean
---@field GetArchitectureType fun(): string
---@field GetAttributeBase fun(pid: number, attributeId: number): number
---@field GetAttributeCount fun(): number
---@field GetAttributeDamage fun(pid: number, attributeId: number): number
---@field GetAttributeId fun(name: string): number
---@field GetAttributeModifier fun(pid: number, attributeId: number): number
---@field GetAttributeName fun(attributeId: number): string
---@field GetAvgPing fun(pid: number): number
---@field GetBirthsign fun(pid: number): string
---@field GetBookChangesSize fun(pid: number): number
---@field GetBookId fun(pid: number, index: integer): string
---@field GetBounty fun(pid: number): number
---@field GetCaseInsensitiveFilename fun(folderPath: string, filename: string): string
---@field GetCell fun(pid: number): string
---@field GetCellStateChangesSize fun(pid: number): number
---@field GetCellStateDescription fun(pid: number, index: integer): string
---@field GetCellStateType fun(pid: number, index: integer): number
---@field GetClassDesc fun(pid: number): string
---@field GetClassMajorAttribute fun(pid: number, slot: number): number
---@field GetClassMajorSkill fun(pid: number, slot: number): number
---@field GetClassMinorSkill fun(pid: number, slot: number): number
---@field GetClassName fun(pid: number): string
---@field GetClassSpecialization fun(pid: number): number
---@field GetClientGlobalFloatValue fun(index: integer): number
---@field GetClientGlobalId fun(index: integer): string
---@field GetClientGlobalIntValue fun(index: integer): integer
---@field GetClientGlobalsSize fun(): integer
---@field GetClientGlobalVariableType fun(index: integer): integer
---@field GetClientLocalFloatValue fun(packetIndex: integer, variableIndex: integer): number
---@field GetClientLocalInternalIndex fun(packetIndex: integer, variableIndex: integer): integer
---@field GetClientLocalIntValue fun(packetIndex: integer, variableIndex: integer): integer
---@field GetClientLocalsSize fun(packetIndex: integer): integer
---@field GetClientLocalVariableType fun(packetIndex: integer, variableIndex: integer): integer
---@field GetContainerChangesSize fun(objectindex: integer): number
---@field GetContainerItemActionCount fun(objectindex: integer, itemindex: integer): number
---@field GetContainerItemCharge fun(objectindex: integer, itemindex: integer): number
---@field GetContainerItemCount fun(objectindex: integer, itemindex: integer): number
---@field GetContainerItemEnchantmentCharge fun(objectindex: integer, itemindex: integer): number
---@field GetContainerItemRefId fun(objectindex: integer, itemindex: integer): string
---@field GetContainerItemSoul fun(objectindex: integer, itemindex: integer): string
---@field GetCooldownChangesSize fun(pid: number): integer
---@field GetCooldownSpellId fun(pid: number, changesIndex: integer): integer
---@field GetCooldownStartDay fun(pid: number, changesIndex: integer): number
---@field GetCooldownStartHour fun(pid: number, changesIndex: integer): number
---@field GetCreatureNameDisplayState fun(pid: number): boolean
---@field GetCreatureRefId fun(pid: number): string
---@field GetCurrentMpNum fun(): number
---@field GetDataPath fun(): string
---@field GetDefaultClass fun(pid: number): string
---@field GetDrawState fun(pid: number): number
---@field GetEquipmentChangesSize fun(pid: number): integer
---@field GetEquipmentChangesSlot fun(pid: number, changesIndex: integer): integer
---@field GetEquipmentItemCharge fun(pid: number, slot: number): number
---@field GetEquipmentItemCount fun(pid: number, slot: number): number
---@field GetEquipmentItemEnchantmentCharge fun(pid: number, slot: number): number
---@field GetEquipmentItemRefId fun(pid: number, slot: number): string
---@field GetEquipmentSize fun(): number
---@field GetExteriorX fun(pid: number): number
---@field GetExteriorY fun(pid: number): number
---@field GetFactionChangesAction fun(pid: number): number
---@field GetFactionChangesSize fun(pid: number): number
---@field GetFactionExpulsionState fun(pid: number, index: integer): boolean
---@field GetFactionId fun(pid: number, index: integer): string
---@field GetFactionRank fun(pid: number, index: integer): number
---@field GetFactionReputation fun(pid: number, index: integer): number
---@field GetFatigueBase fun(pid: number): number
---@field GetFatigueCurrent fun(pid: number): number
---@field GetHair fun(pid: number): string
---@field GetHead fun(pid: number): string
---@field GetHealthBase fun(pid: number): number
---@field GetHealthCurrent fun(pid: number): number
---@field GetInventoryChangesAction fun(pid: number): number
---@field GetInventoryChangesSize fun(pid: number): number
---@field GetInventoryItemCharge fun(pid: number, index: integer): number
---@field GetInventoryItemCount fun(pid: number, index: integer): number
---@field GetInventoryItemEnchantmentCharge fun(pid: number, index: integer): number
---@field GetInventoryItemRefId fun(pid: number, index: integer): string
---@field GetInventoryItemSoul fun(pid: number, index: integer): string
---@field GetIP fun(pid: number): string
---@field GetIsMale fun(pid: number): number
---@field GetJournalChangesSize fun(pid: number): number
---@field GetJournalItemActorRefId fun(pid: number, index: integer): string
---@field GetJournalItemIndex fun(pid: number, index: integer): integer
---@field GetJournalItemQuest fun(pid: number, index: integer): string
---@field GetJournalItemType fun(pid: number, index: integer): number
---@field GetKillChangesSize fun(): number
---@field GetKillNumber fun(index: integer): number
---@field GetKillRefId fun(index: integer): string
---@field GetLastPlayerId fun(): number
---@field GetLevel fun(pid: number): number
---@field GetLevelProgress fun(pid: number): number
---@field GetMagickaBase fun(pid: number): number
---@field GetMagickaCurrent fun(pid: number): number
---@field GetMapChangesSize fun(): number
---@field GetMapTileCellX fun(index: integer): number
---@field GetMapTileCellY fun(index: integer): number
---@field GetMarkCell fun(pid: number): string
---@field GetMarkPosX fun(pid: number): number
---@field GetMarkPosY fun(pid: number): number
---@field GetMarkPosZ fun(pid: number): number
---@field GetMarkRotX fun(pid: number): number
---@field GetMarkRotZ fun(pid: number): number
---@field GetMaxPlayers fun(): number
---@field GetMiscellaneousChangeType fun(pid: number): number
---@field GetModel fun(pid: number): string
---@field GetName fun(pid: number): string
---@field GetObjectActivatingMpNum fun(index: integer): number
---@field GetObjectActivatingName fun(index: integer): string
---@field GetObjectActivatingPid fun(index: integer): number
---@field GetObjectActivatingRefId fun(index: integer): string
---@field GetObjectActivatingRefNum fun(index: integer): number
---@field GetObjectCharge fun(index: integer): number
---@field GetObjectCount fun(index: integer): number
---@field GetObjectDialogueChoiceTopic fun(packetIndex: integer): string
---@field GetObjectDialogueChoiceType fun(packetIndex: integer): integer
---@field GetObjectDoorState fun(index: integer): number
---@field GetObjectEnchantmentCharge fun(index: integer): number
---@field GetObjectGoldPool fun(packetIndex: integer): integer
---@field GetObjectGoldValue fun(index: integer): number
---@field GetObjectHitBlock fun(packetIndex: integer): boolean
---@field GetObjectHitDamage fun(packetIndex: integer): number
---@field GetObjectHitKnockdown fun(packetIndex: integer): boolean
---@field GetObjectHitSuccess fun(packetIndex: integer): boolean
---@field GetObjectHittingMpNum fun(packetIndex: integer): integer
---@field GetObjectHittingPid fun(packetIndex: integer): integer
---@field GetObjectHittingRefId fun(packetIndex: integer): string
---@field GetObjectHittingRefNum fun(packetIndex: integer): integer
---@field GetObjectLastGoldRestockDay fun(packetIndex: integer): integer
---@field GetObjectLastGoldRestockHour fun(packetIndex: integer): number
---@field GetObjectListAction fun(): number
---@field GetObjectListClientScript fun(): string
---@field GetObjectListConsoleCommand fun(): string
---@field GetObjectListContainerSubAction fun(): number
---@field GetObjectListOrigin fun(): number
---@field GetObjectListSize fun(): number
---@field GetObjectLockLevel fun(index: integer): number
---@field GetObjectMpNum fun(index: integer): number
---@field GetObjectPid fun(index: integer): number
---@field GetObjectPosX fun(index: integer): number
---@field GetObjectPosY fun(index: integer): number
---@field GetObjectPosZ fun(index: integer): number
---@field GetObjectRefId fun(index: integer): string
---@field GetObjectRefNum fun(index: integer): number
---@field GetObjectRotX fun(index: integer): number
---@field GetObjectRotY fun(index: integer): number
---@field GetObjectRotZ fun(index: integer): number
---@field GetObjectScale fun(index: integer): number
---@field GetObjectSoul fun(index: integer): string
---@field GetObjectSoundId fun(packetIndex: integer): string
---@field GetObjectState fun(index: integer): boolean
---@field GetObjectSummonDuration fun(index: integer): number
---@field GetObjectSummonEffectId fun(packetIndex: integer): number
---@field GetObjectSummonerMpNum fun(index: integer): number
---@field GetObjectSummonerPid fun(index: integer): number
---@field GetObjectSummonerRefId fun(index: integer): string
---@field GetObjectSummonerRefNum fun(index: integer): number
---@field GetObjectSummonSpellId fun(packetIndex: integer): string
---@field GetObjectSummonState fun(index: integer): boolean
---@field GetOperatingSystemType fun(): string
---@field GetPlayerKillerMpNum fun(pid: number): number
---@field GetPlayerKillerName fun(pid: number): string
---@field GetPlayerKillerPid fun(pid: number): number
---@field GetPlayerKillerRefId fun(pid: number): string
---@field GetPlayerKillerRefNum fun(pid: number): number
---@field GetPluginEnforcementState fun(): boolean
---@field GetPort fun(): number
---@field GetPosX fun(pid: number): number
---@field GetPosY fun(pid: number): number
---@field GetPosZ fun(pid: number): number
---@field GetPreviousCellPosX fun(pid: number): number
---@field GetPreviousCellPosY fun(pid: number): number
---@field GetPreviousCellPosZ fun(pid: number): number
---@field GetProtocolVersion fun(): string
---@field GetQuickKeyChangesSize fun(pid: number): number
---@field GetQuickKeyItemId fun(pid: number, index: integer): string
---@field GetQuickKeySlot fun(pid: number, index: integer): number
---@field GetQuickKeyType fun(pid: number, index: integer): number
---@field GetRace fun(pid: number): string
---@field GetRecordAutoCalc fun(index: integer): number
---@field GetRecordBaseId fun(index: integer): string
---@field GetRecordCharge fun(index: integer): number
---@field GetRecordCost fun(index: integer): number
---@field GetRecordCount fun(): number
---@field GetRecordEffectArea fun(recordindex: integer, effectindex: integer): number
---@field GetRecordEffectAttribute fun(recordindex: integer, effectindex: integer): number
---@field GetRecordEffectCount fun(recordindex: integer): number
---@field GetRecordEffectDuration fun(recordindex: integer, effectindex: integer): number
---@field GetRecordEffectId fun(recordindex: integer, effectindex: integer): number
---@field GetRecordEffectMagnitudeMax fun(recordindex: integer, effectindex: integer): number
---@field GetRecordEffectMagnitudeMin fun(recordindex: integer, effectindex: integer): number
---@field GetRecordEffectRangeType fun(recordindex: integer, effectindex: integer): number
---@field GetRecordEffectSkill fun(recordindex: integer, effectindex: integer): number
---@field GetRecordEnchantmentCharge fun(index: integer): number
---@field GetRecordEnchantmentId fun(index: integer): string
---@field GetRecordFlags fun(index: integer): number
---@field GetRecordIcon fun(index: integer): string
---@field GetRecordId fun(index: integer): string
---@field GetRecordModel fun(index: integer): string
---@field GetRecordName fun(index: integer): string
---@field GetRecordQuantity fun(recordIndex: integer): integer
---@field GetRecordScript fun(index: integer): string
---@field GetRecordSubtype fun(index: integer): number
---@field GetRecordType fun(): number
---@field GetRecordValue fun(index: integer): number
---@field GetRecordWeight fun(index: integer): number
---@field GetRegion fun(pid: number): string
---@field GetReputation fun(pid: number): number
---@field GetRotX fun(pid: number): number
---@field GetRotZ fun(pid: number): number
---@field GetScale fun(pid: number): number
---@field GetScriptErrorIgnoringState fun(): boolean
---@field GetSelectedSpellId fun(pid: number): string
---@field GetServerVersion fun(): string
---@field GetSHA256Hash fun(input: string): string
---@field GetSkillBase fun(pid: number, skillId: number): number
---@field GetSkillCount fun(): number
---@field GetSkillDamage fun(pid: number, skillId: number): number
---@field GetSkillId fun(name: string): number
---@field GetSkillIncrease fun(pid: number, attributeId: number): number
---@field GetSkillModifier fun(pid: number, skillId: number): number
---@field GetSkillName fun(skillId: number): string
---@field GetSkillProgress fun(pid: number, skillId: number): number
---@field GetSneakState fun(pid: number): boolean
---@field GetSpellbookChangesAction fun(pid: number): number
---@field GetSpellbookChangesSize fun(pid: number): number
---@field GetSpellId fun(pid: number, index: integer): string
---@field GetSpellsActiveCasterMpNum fun(pid: number, changesIndex: integer): integer
---@field GetSpellsActiveCasterPid fun(pid: number, changesIndex: integer): number
---@field GetSpellsActiveCasterRefId fun(pid: number, changesIndex: integer): string
---@field GetSpellsActiveCasterRefNum fun(pid: number, changesIndex: integer): integer
---@field GetSpellsActiveChangesAction fun(pid: number): integer
---@field GetSpellsActiveChangesSize fun(pid: number): integer
---@field GetSpellsActiveDisplayName fun(pid: number, changesIndex: integer): string
---@field GetSpellsActiveEffectArg fun(pid: number, changesIndex: integer, effectIndex: integer): integer
---@field GetSpellsActiveEffectCount fun(pid: number, changesIndex: integer): integer
---@field GetSpellsActiveEffectDuration fun(pid: number, changesIndex: integer, effectIndex: integer): number
---@field GetSpellsActiveEffectId fun(pid: number, changesIndex: integer, effectIndex: integer): integer
---@field GetSpellsActiveEffectMagnitude fun(pid: number, changesIndex: integer, effectIndex: integer): number
---@field GetSpellsActiveEffectTimeLeft fun(pid: number, changesIndex: integer, effectIndex: integer): number
---@field GetSpellsActiveId fun(pid: number, changesIndex: integer): string
---@field GetSpellsActiveStackingState fun(pid: number, changesIndex: integer): boolean
---@field GetTopicChangesSize fun(pid: number): number
---@field GetTopicId fun(pid: number, index: integer): string
---@field GetUsedItemCharge fun(pid: number): number
---@field GetUsedItemCount fun(pid: number): number
---@field GetUsedItemEnchantmentCharge fun(pid: number): number
---@field GetUsedItemRefId fun(pid: number): string
---@field GetUsedItemSoul fun(pid: number): string
---@field GetVideoFilename fun(index: integer): string
---@field GetWeatherCurrent fun(): number
---@field GetWeatherNext fun(): number
---@field GetWeatherQueued fun(): number
---@field GetWeatherRegion fun(): string
---@field GetWeatherTransitionFactor fun(): number
---@field HasItemEquipped fun(pid: number, refId: string): boolean
---@field HasPassword fun(): boolean
---@field InputDialog fun(pid: number, id: number, label: string, note: string)
---@field IsChangingRegion fun(pid: number): boolean
---@field IsClassDefault fun(pid: number): number
---@field IsInExterior fun(pid: number): boolean
---@field IsObjectDroppedByPlayer fun(packetIndex: integer): boolean
---@field IsObjectPlayer fun(index: integer): boolean
---@field IsWerewolf fun(pid: number): boolean
---@field Jail fun(pid: number, jailDays: number, ignoreJailTeleportation: boolean, ignoreJailSkillIncreases: boolean, jailProgressText: string, jailEndText: string)
---@field Kick fun(pid: number)
---@field ListBox fun(pid: number, id: number, label: string, items: string)
---@field LoadMapTileImageFile fun(cellX: number, cellY: number, filePath: string)
---@field LogAppend fun(level: number, message: string)
---@field LogMessage fun(level: number, message: string)
---@field MessageBox fun(pid: number, id: number, message: string)
---@field PasswordDialog fun(pid: number, id: number, label: string, note: string)
---@field PlayAnimation fun(pid: number, groupname: string, mode: number, count: number, persist: boolean)
---@field PlaySpeech fun(pid: number, sound: string)
---@field ReadCellActorList fun(cellDescription: string)
---@field ReadReceivedActorList fun()
---@field ReadReceivedObjectList fun()
---@field ReadReceivedWorldstate fun()
---@field RestartTimer fun(timerId: number, time: number)
---@field Resurrect fun(pid: number, type: number)
---@field SaveMapTileImageFile fun(index: integer, filePath: string)
---@field SendActorAI fun(sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendActorAuthority fun()
---@field SendActorCellChange fun(sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendActorDeath fun()
---@field SendActorEquipment fun(sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendActorList fun()
---@field SendActorPosition fun(sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendActorSpeech fun(sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendActorSpellsActiveChanges fun()
---@field SendActorStatsDynamic fun(sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendAlliedPlayers fun(pid: number, sendToOtherPlayers: boolean|nil)
---@field SendAttributes fun(pid: number)
---@field SendBaseInfo fun(pid: number)
---@field SendBookChanges fun(pid: number, sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendBounty fun(pid: number)
---@field SendCell fun(pid: number)
---@field SendCellReset fun(pid: number, sendToOtherPlayers: boolean)
---@field SendClass fun(pid: number)
---@field SendClientScriptGlobal fun(pid: number, sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendClientScriptLocal fun(forEveryone: boolean)
---@field SendClientScriptSettings fun(sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendConsoleCommand fun(sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendContainer fun(sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendCooldownChanges fun(pid: number)
---@field SendDoorDestination fun(sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendDoorState fun(sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendEquipment fun(pid: number)
---@field SendFactionChanges fun(pid: number, sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendInventoryChanges fun(pid: number, sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendItemUse fun(pid: number)
---@field SendJournalChanges fun(pid: number, sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendKillChanges fun(pid: number, sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendLevel fun(pid: number)
---@field SendMarkLocation fun(pid: number)
---@field SendMessage fun(pid: number, message: string, sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendMomentum fun(pid: number)
---@field SendObjectActivate fun(sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendObjectDelete fun(sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendObjectDialogueChoice fun(sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendObjectLock fun(sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendObjectMiscellaneous fun(forEveryone: boolean)
---@field SendObjectPlace fun(sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendObjectRestock fun(sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendObjectRotate fun(sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendObjectScale fun(sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendObjectSound fun(sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendObjectSpawn fun(sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendObjectState fun(sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendObjectTrap fun(sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendPos fun(pid: number)
---@field SendQuickKeyChanges fun(pid: number)
---@field SendRecordDynamic fun(pid: number, sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendReputation fun(pid: number, sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendSelectedSpell fun(pid: number)
---@field SendSettings fun(pid: number)
---@field SendShapeshift fun(pid: number)
---@field SendSkills fun(pid: number)
---@field SendSpellbookChanges fun(pid: number, sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendSpellsActiveChanges fun(pid: number, sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendStatsDynamic fun(pid: number)
---@field SendTopicChanges fun(pid: number, sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendVideoPlay fun(sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendWorldCollisionOverride fun(pid: number, sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendWorldDestinationOverride fun(pid: number)
---@field SendWorldKillCount fun(pid: number, sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendWorldMap fun(pid: number, sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendWorldRegionAuthority fun(pid: number)
---@field SendWorldTime fun(pid: number, sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SendWorldWeather fun(pid: number, sendToOtherPlayers: boolean|nil, skipAttachedPlayer: boolean|nil)
---@field SetActorAIAction fun(action: number)
---@field SetActorAICoordinates fun(x: number, y: number, z: number)
---@field SetActorAIDistance fun(distance: number)
---@field SetActorAIDuration fun(duration: number)
---@field SetActorAIRepetition fun(shouldRepeat: boolean)
---@field SetActorAITargetToObject fun(refNum: number, mpNum: number)
---@field SetActorAITargetToPlayer fun(pid: number)
---@field SetActorCell fun(cellDescription: string)
---@field SetActorCollisionState fun(state: boolean)
---@field SetActorDeathInstant fun(isInstant: boolean)
---@field SetActorDeathState fun(deathstate: integer)
---@field SetActorFatigueBase fun(value: number)
---@field SetActorFatigueCurrent fun(value: number)
---@field SetActorFatigueModified fun(value: number)
---@field SetActorHealthBase fun(value: number)
---@field SetActorHealthCurrent fun(value: number)
---@field SetActorHealthModified fun(value: number)
---@field SetActorListAction fun(action: number)
---@field SetActorListCell fun(cellDescription: string)
---@field SetActorListPid fun(pid: number)
---@field SetActorMagickaBase fun(value: number)
---@field SetActorMagickaCurrent fun(value: number)
---@field SetActorMagickaModified fun(value: number)
---@field SetActorMpNum fun(mpNum: number)
---@field SetActorPosition fun(x: number, y: number, z: number)
---@field SetActorRefId fun(refId: string)
---@field SetActorRefNum fun(refNum: number)
---@field SetActorRotation fun(x: number, y: number, z: number)
---@field SetActorSound fun(sound: string)
---@field SetAttributeBase fun(pid: number, attributeId: number, value: number)
---@field SetAttributeDamage fun(pid: number, attributeId: number, value: number)
---@field SetAuthorityRegion fun(authorityRegion: string)
---@field SetBedRestAllowed fun(pid: number, state: boolean)
---@field SetBirthsign fun(pid: number, name: string)
---@field SetBounty fun(pid: number, value: number)
---@field SetCell fun(pid: number, cellDescription: string)
---@field SetCharGenStage fun(pid: number, currentStage: number, endStage: number)
---@field SetClassDesc fun(pid: number, desc: string)
---@field SetClassMajorAttribute fun(pid: number, slot: number, attrId: number)
---@field SetClassMajorSkill fun(pid: number, slot: number, skillId: number)
---@field SetClassMinorSkill fun(pid: number, slot: number, skillId: number)
---@field SetClassName fun(pid: number, name: string)
---@field SetClassSpecialization fun(pid: number, spec: number)
---@field SetConsoleAllowed fun(pid: number, state: boolean)
---@field SetContainerItemActionCountByIndex fun(objectindex: integer, itemindex: integer, actionCount: number)
---@field SetContainerItemCharge fun(charge: number)
---@field SetContainerItemCount fun(count: number)
---@field SetContainerItemEnchantmentCharge fun(enchantmentCharge: number)
---@field SetContainerItemRefId fun(refId: string)
---@field SetContainerItemSoul fun(soul: string)
---@field SetCreatureNameDisplayState fun(pid: number, displayState: boolean)
---@field SetCreatureRefId fun(pid: number, refId: string)
---@field SetCurrentMpNum fun(mpNum: number)
---@field SetDataFileEnforcementState fun(value: boolean)
---@field SetDay fun(day: number)
---@field SetDaysPassed fun(daysPassed: number)
---@field SetDefaultClass fun(pid: number, id: string)
---@field SetDifficulty fun(pid: number, difficulty: number)
---@field SetEnforcedLogLevel fun(pid: number, enforcedLogLevel: number)
---@field SetExterior fun(pid: number, xCoord: integer, yCoord: integer)
---@field SetExteriorCell fun(pid: number, x: number, y: number)
---@field SetFactionChangesAction fun(pid: number, action: number)
---@field SetFactionExpulsionState fun(expulsionState: boolean)
---@field SetFactionId fun(factionId: string)
---@field SetFactionRank fun(rank: number)
---@field SetFactionReputation fun(reputation: number)
---@field SetFatigueBase fun(pid: number, value: number)
---@field SetFatigueCurrent fun(pid: number, value: number)
---@field SetGameMode fun(gameMode: string)
---@field SetGameSettingValue fun(pid: number, settingName: string, settingValue: string)
---@field SetHair fun(pid: number, hairstyle: string)
---@field SetHead fun(pid: number, head: string)
---@field SetHealthBase fun(pid: number, value: number)
---@field SetHealthCurrent fun(pid: number, value: number)
---@field SetHostname fun(name: string)
---@field SetHour fun(hour: number)
---@field SetInventoryChangesAction fun(pid: number, action: number)
---@field SetIsMale fun(pid: number, state: number)
---@field SetLevel fun(pid: number, value: number)
---@field SetLevelProgress fun(pid: number, value: number)
---@field SetMagickaBase fun(pid: number, value: number)
---@field SetMagickaCurrent fun(pid: number, value: number)
---@field SetMapVisibility fun(targetPid: number, affectedPid: number, state: number)
---@field SetMapVisibilityAll fun(targetPid: number, state: number)
---@field SetMarkCell fun(pid: number, cellDescription: string)
---@field SetMarkPos fun(pid: number, x: number, y: number, z: number)
---@field SetMarkRot fun(pid: number, x: number, z: number)
---@field SetModel fun(pid: number, model: string)
---@field SetMomentum fun(pid: number, x: number, y: number, z: number)
---@field SetMonth fun(month: number)
---@field SetName fun(pid: number, name: string)
---@field SetObjectActivatingPid fun(pid: number)
---@field SetObjectCharge fun(charge: number)
---@field SetObjectCount fun(count: number)
---@field SetObjectDisarmState fun(disarmState: boolean)
---@field SetObjectDoorDestinationCell fun(cellDescription: string)
---@field SetObjectDoorDestinationPosition fun(x: number, y: number, z: number)
---@field SetObjectDoorDestinationRotation fun(x: number, z: number)
---@field SetObjectDoorState fun(doorState: number)
---@field SetObjectDoorTeleportState fun(teleportState: boolean)
---@field SetObjectEnchantmentCharge fun(enchantmentCharge: number)
---@field SetObjectGoldValue fun(goldValue: number)
---@field SetObjectListAction fun(action: number)
---@field SetObjectListCell fun(cellDescription: string)
---@field SetObjectListConsoleCommand fun(consoleCommand: string)
---@field SetObjectListContainerSubAction fun(actionType: number)
---@field SetObjectListPid fun(pid: number)
---@field SetObjectLockLevel fun(lockLevel: number)
---@field SetObjectMpNum fun(mpNum: number)
---@field SetObjectPosition fun(x: number, y: number, z: number)
---@field SetObjectRefId fun(refId: string)
---@field SetObjectRefNum fun(refNum: number)
---@field SetObjectRotation fun(x: number, y: number, z: number)
---@field SetObjectScale fun(scale: number)
---@field SetObjectSoul fun(soul: string)
---@field SetObjectState fun(objectState: boolean)
---@field SetObjectSummonDuration fun(summonDuration: number)
---@field SetObjectSummonState fun(summonState: boolean)
---@field SetPhysicsFramerate fun(pid: number, physicsFramerate: number)
---@field SetPlacedObjectCollisionState fun(state: boolean)
---@field SetPlayerAsObject fun(pid: number)
---@field SetPlayerCollisionState fun(state: boolean)
---@field SetPluginEnforcementState fun(state: boolean)
---@field SetPos fun(pid: number, x: number, y: number, z: number)
---@field SetRace fun(pid: number, race: string)
---@field SetRecordAIFight fun(aiFight: number)
---@field SetRecordArmorRating fun(armorRating: number)
---@field SetRecordAutoCalc fun(autoCalc: number)
---@field SetRecordBaseId fun(baseId: string)
---@field SetRecordBodyPartIdForFemale fun(partId: string)
---@field SetRecordBodyPartIdForMale fun(partId: string)
---@field SetRecordBodyPartType fun(partType: number)
---@field SetRecordCharge fun(charge: number)
---@field SetRecordClass fun(charClass: string)
---@field SetRecordCost fun(cost: number)
---@field SetRecordDamageChop fun(minDamage: number, maxDamage: number)
---@field SetRecordDamageSlash fun(minDamage: number, maxDamage: number)
---@field SetRecordDamageThrust fun(minDamage: number, maxDamage: number)
---@field SetRecordEffectArea fun(area: number)
---@field SetRecordEffectAttribute fun(attributeId: number)
---@field SetRecordEffectDuration fun(duration: number)
---@field SetRecordEffectId fun(effectId: number)
---@field SetRecordEffectMagnitudeMax fun(magnitudeMax: number)
---@field SetRecordEffectMagnitudeMin fun(magnitudeMin: number)
---@field SetRecordEffectRangeType fun(rangeType: number)
---@field SetRecordEffectSkill fun(skillId: number)
---@field SetRecordEnchantmentCharge fun(enchantmentCharge: number)
---@field SetRecordEnchantmentId fun(enchantmentId: string)
---@field SetRecordEnchantmentIdByIndex fun(index: integer, enchantmentId: string)
---@field SetRecordFaction fun(faction: string)
---@field SetRecordFatigue fun(fatigue: number)
---@field SetRecordFlags fun(flags: number)
---@field SetRecordGender fun(gender: number)
---@field SetRecordHair fun(hair: string)
---@field SetRecordHead fun(head: string)
---@field SetRecordHealth fun(health: number)
---@field SetRecordIcon fun(icon: string)
---@field SetRecordId fun(id: string)
---@field SetRecordIdByIndex fun(index: integer, id: string)
---@field SetRecordInventoryBaseId fun(inventoryBaseId: string)
---@field SetRecordInventoryItemCount fun(count: number)
---@field SetRecordInventoryItemId fun(itemId: string)
---@field SetRecordKeyState fun(keyState: boolean)
---@field SetRecordLevel fun(level: number)
---@field SetRecordMagicka fun(magicka: number)
---@field SetRecordModel fun(model: string)
---@field SetRecordName fun(name: string)
---@field SetRecordRace fun(race: string)
---@field SetRecordReach fun(reach: number)
---@field SetRecordScript fun(script: string)
---@field SetRecordScrollState fun(scrollState: boolean)
---@field SetRecordSkillId fun(skillId: number)
---@field SetRecordSpeed fun(speed: number)
---@field SetRecordSubtype fun(subtype: number)
---@field SetRecordText fun(text: string)
---@field SetRecordType fun(type: number)
---@field SetRecordValue fun(value: number)
---@field SetRecordWeight fun(weight: number)
---@field SetReputation fun(pid: number, value: number)
---@field SetResetStats fun(pid: number, resetStats: boolean)
---@field SetRot fun(pid: number, x: number, z: number)
---@field SetRuleString fun(key: string, value: string)
---@field SetRuleValue fun(key: string, value: number)
---@field SetScale fun(pid: number, scale: number)
---@field SetScriptErrorIgnoringState fun(state: boolean)
---@field SetSelectedSpellId fun(pid: number, spellId: string)
---@field SetServerPassword fun(password: string)
---@field SetSkillBase fun(pid: number, skillId: number, value: number)
---@field SetSkillDamage fun(pid: number, skillId: number, value: number)
---@field SetSkillIncrease fun(pid: number, attributeId: number, value: number)
---@field SetSkillProgress fun(pid: number, skillId: number, value: number)
---@field SetSpellbookChangesAction fun(pid: number, action: number)
---@field SetTimeScale fun(timeScale: number)
---@field SetVRSettingValue fun(pid: number, name: string, value: string)
---@field SetWaitAllowed fun(pid: number, state: boolean)
---@field SetWeatherCurrent fun(currentWeather: number)
---@field SetWeatherForceState fun(forceState: boolean)
---@field SetWeatherNext fun(nextWeather: number)
---@field SetWeatherQueued fun(queuedWeather: number)
---@field SetWeatherRegion fun(region: string)
---@field SetWeatherTransitionFactor fun(transitionFactor: number)
---@field SetWerewolfState fun(pid: number, isWerewolf: boolean)
---@field SetWildernessRestAllowed fun(pid: number, state: boolean)
---@field SetYear fun(year: number)
---@field StartTimer fun(timerId: number)
---@field StopServer fun(code: number)
---@field StopTimer fun(timerId: number)
---@field UnbanAddress fun(ipAddress: string)
---@field UnequipActorItem fun(slot: number)
---@field UnequipItem fun(pid: number, slot: number)
---@field UseActorCollisionForPlacedObjects fun(useActorCollision: boolean)
